# Github Actions video test

name: test-video

# Action on push or pull request only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  run_test:
    
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Git clone 
      uses: actions/checkout@v2

    - name: Current folder
      run: ls -la

    - name: Install
      run: npm install
    
    - name: Check folder
      run: ls -la
   
    - name: Install Chrome
      run: sudo apt-get update && apt-get install -y wget --no-install-recommends \
           && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
           && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
           && apt-get update \
           && apt-get install -y google-chrome-unstable \
           --no-install-recommends \
           && rm -rf /var/lib/apt/lists/* \
           && apt-get purge --auto-remove -y curl \
           && rm -rf /src/*.deb 
           
    - name: Run test
      run: npx codeceptjs run --steps
      env:
         CHROME_PATH: /usr/bin/google-chrome 
